### ISSUE TITLE
Error in recent version of python files with added library

### ISSUE THREAD

**Issue by dhjpolymath** [km-git-acc/dbn_upper_bound#8]
Traceback (most recent call last):
  File "H_t_probable_first_1000_zeroes", line 19, in <module>
    Ht_root = fsolve(Ht_real,nearby_root,args=(t,))[0]
  File "C:\Users\******\Anaconda3\lib\site-packages\scipy\optimize\minpack.py", line 146, in fsolve
    res = _root_hybr(func, x0, args, jac=fprime, **options)
  File "C:\Users\******\Anaconda3\lib\site-packages\scipy\optimize\minpack.py", line 212, in _root_hybr
    shape, dtype = _check_func('fsolve', 'func', func, x0, args, n, (n,))
  File "C:\Users\******\Anaconda3\lib\site-packages\scipy\optimize\minpack.py", line 26, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "C:\Users\******\Downloads\dbn_upper_bound-master\python\Ht_real_compute.py", line 12, in Ht_real
    return quad(Ht_real_integrand, 0, 10, args=(z,t))
  File "C:\Users\******\Anaconda3\lib\site-packages\scipy\integrate\quadpack.py", line 323, in quad
    points)
  File "C:\Users\******\Anaconda3\lib\site-packages\scipy\integrate\quadpack.py", line 388, in _quad
    return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)
TypeError: can't convert complex to float
------------------------------------------------------------------------------
This is output on an attempt to run the current version with python3 after only changing print "x" lines to print("x").

**Comment by km-git-acc** [comment]
@dhjpolymath, these issues cropped up after enabling complex calculations. Firstly, added you as a collaborator. Also, use the Ht_real function directly from the utility file. The line importing ht_real_compute file can be removed. Does the issue crop up after that change?

**Comment by dhjpolymath** [comment]
@km-git-acc Upon removing from utility, no. Resolved.

**Comment by km-git-acc** [comment]
Great. I will have to be more careful from now on. I have always coded on my personal computer as a hobby and never as part of a project before, so going through a learning phase :)
